spring:
  application:
    name: service-register
server:
  port: 8181
eureka:
  client:
    service-url:
          defaultZone: http://localhost:8180/eureka
   # register-with-eureka: false
   # fetch-registry: false
  instance:
    hostname: localhost
  server:
    batch-replication: true

info:
   app:
     name: service-register
     description: 基于eureka服务注册与发现
     version: 1.0.0
   base:
     author: xwolf
     description: spring cloud eureka learn
     team-name: xwolf-team
     email:  snowxwolf@foxmail.com
