server:
  port: 8380
eureka:
  client:
    service-url:
          defaultZone: http://localhost:8180/eureka,http://localhost:8181/eureka
  instance:
    hostname: localhost
spring:
  application:
    name: service-ribbon
  cloud:
    loadbalancer:
      retry:
        enabled: true
service-ribbon:
          ribbon:
             NFLoadBalancerRuleClassName:  com.netflix.loadbalancer.WeightedResponseTimeRule
             #请求连接的超时时间
             ConnectTimeOut: 10
             ReadTimeout:    10
             OkToRetryOnAllOperations: true
             MaxAutoRetriesNextServer: 2
             MaxAutoRetries: 1
#断路器的超时时间需要大于ribbon的超时时间，不然不会触发重试。
hystrix:
    command:
        default:
             :execution:
                    isolation:
                           thread:
                                timeoutInMilliseconds: 12

info:
   app:
     name: service-ribbon
     description: 基于eureka HA 服务注册与发现ribbon
     version: 1.0.0
   base:
     author: xwolf
     description: spring cloud ribbon learn
     team-name: xwolf-team
     email:  snowxwolf@foxmail.com

logging:
  level:
      - info
