spring:
  application:
    name: service-register
server:
  port: 8081

eureka:
  client:
    service-url:
          defaultZone: http://localhost:8081/eureka
    register-with-eureka: false
    fetch-registry: false
    client-data-accept:
  instance:
    hostname: localhost

