server:
  port: 8580
spring:
  profiles:
    active: dev
  config:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xwolf191/learn-spring-cloud
          username: xxxxx
          password: xxxxx
          default-label: master
      label: master




