server:
  port: 8082
eureka:
  client:
    service-url:
          defaultZone: http://localhost:8081/eureka
  instance:
    hostname: localhost
spring:
  application:
    name: service-discovery-localhsot

info:
   app:
     name: service-discovery
     description: 基于eureka服务注册与发现
   base:
     author: xwolf
     description: spring cloud eureka learn
     team-name: xwolf-team
     email:  snowxwolf@foxmail.com
