server:
  port: 8480
eureka:
  client:
    service-url:
          defaultZone: http://localhost:8180/eureka,http://localhost:8181/eureka
  instance:
    hostname: localhost
spring:
  application:
    name: service-feign
feign:
   hystrix:
      enabled: true

info:
   app:
     name: service-feign
     description: feign声明式服务调用
     version: 1.0.0
   base:
     author: xwolf
     description: spring cloud feign learn
     team-name: xwolf-team
     email:  snowxwolf@foxmail.com

logging:
  level:
      - info
ribbon:
  ConnectTimeout: 400
  ReadTimeout: 500
